import fs from 'node:fs'
import path from 'node:path'
import * as esbuild from 'esbuild'
import { iconMask } from './icons.mjs'

const here = import.meta.dirname
const generatedDir = path.join(here, '../src/styles/generated')

/** Mirrors `src/design/Markdown.ts`, so a docs callout wears the app's glyph. */
const calloutIcons = {
	note: 'info',
	tip: 'lightbulb',
	important: 'message-square-warning',
	warning: 'triangle-alert',
	caution: 'octagon-alert',
}

/** Evaluates `src/design`'s lit `css` fragments in Node (tag swapped for `css-shim.mjs`) into plain CSS. */
export async function emitTokens() {
	const bundle = await esbuild.build({
		entryPoints: [path.join(here, 'tokens.entry.ts')],
		bundle: true,
		format: 'esm',
		write: false,
		alias: { '@a11d/lit': path.join(here, 'css-shim.mjs') },
		logLevel: 'silent',
	})

	const source = bundle.outputFiles[0].text
	const module = await import(`data:text/javascript;base64,${Buffer.from(source).toString('base64')}`)
	const css = module.fragments.map(fragment => fragment.cssText.trim()).join('\n\n')

	fs.mkdirSync(generatedDir, { recursive: true })
	fs.writeFileSync(path.join(generatedDir, 'mitra.css'), [
		'/* Generated by website/tools/tokens.mjs from src/design. Do not edit. */',
		'',
		css,
		'',
	].join('\n'))

	fs.writeFileSync(path.join(generatedDir, 'callouts.css'), [
		'/* Generated by website/tools/tokens.mjs from lucide and src/design/Markdown.ts. Do not edit. */',
		'',
		...Object.entries(calloutIcons).map(([kind, icon]) =>
			`.markdown-alert-${kind} > .markdown-alert-title::before { mask-image: ${iconMask(icon)}; }`),
		'',
	].join('\n'))
}
