// <auto-generated>
// ⚠️ Do not edit this file manually. Run `npm run i18n:generate` to regenerate it from the `t('…')`
// calls in the frontend. It augments @3mo/localization's `LocalizableStringKeys` so `t(…)` autocompletes
// the known keys and flags typos, while still accepting any string.
/* eslint-disable */
export {}

declare global {
	interface LocalizableStringKeys {
		"+ end date": unknown
		"+${count:number} more": unknown
		"${count:number} min": unknown
		"${count:pluralityNumber} days": unknown
		"${count:pluralityNumber} hours": unknown
		"${count:pluralityNumber} months": unknown
		"${count:pluralityNumber} weeks": unknown
		"${count:pluralityNumber} years": unknown
		"${span} before": unknown
		"${status} — click to toggle, Alt-click for options": unknown
		"About": unknown
		"about build info release commit": unknown
		"Account": unknown
		"Add integration": unknown
		"Add Integration": unknown
		"Add reminder": unknown
		"Add time zone": unknown
		"After": unknown
		"All day": unknown
		"All entries": unknown
		"Amount": unknown
		"App-Specific Password": unknown
		"Apple ID": unknown
		"At start": unknown
		"At start of event": unknown
		"Back": unknown
		"back earlier": unknown
		"before": unknown
		"before at ${time}": unknown
		"Calendar options": unknown
		"Cancelled": unknown
		"changelog release notes news updates version": unknown
		"close": unknown
		"Close": unknown
		"collapse expand calendars": unknown
		"Commands": unknown
		"Commit": unknown
		"Connect": unknown
		"connect caldav account calendar": unknown
		"Connecting…": unknown
		"Continue with Google": unknown
		"Copy": unknown
		"Copy Version": unknown
		"Create Entry": unknown
		"Custom…": unknown
		"days": unknown
		"Default for new entries — click to unset": unknown
		"Delete": unknown
		"Delete repeating entry": unknown
		"Delete the locally cached entries and import everything from the source again": unknown
		"Delete the locally cached entries of every enabled source and import everything again": unknown
		"Description": unknown
		"Does not repeat": unknown
		"Doing": unknown
		"Done": unknown
		"Double-click to rename": unknown
		"Draft": unknown
		"Edit": unknown
		"Edit integration": unknown
		"Edit repeating entry": unknown
		"End date": unknown
		"End time": unknown
		"Ends": unknown
		"Entries": unknown
		"Events": unknown
		"Every": unknown
		"forward later": unknown
		"Go to Date…": unknown
		"Go to Today": unknown
		"Google account": unknown
		"Google.ConfigurationHint": unknown
		"Google.ConsentHint": unknown
		"Hide calendar": unknown
		"hours": unknown
		"Include time": unknown
		"Install as an App": unknown
		"Install mitra as an app — it gets its own window, and notifications appear under its own name and icon": unknown
		"Integration options": unknown
		"Integration Token": unknown
		"Interval": unknown
		"jump navigate pick specific day month year": unknown
		"Location": unknown
		"minutes": unknown
		"Month": unknown
		"Month View": unknown
		"navigate": unknown
		"Never": unknown
		"New dev build — ${count:pluralityNumber} commits ahead": unknown
		"new event task add": unknown
		"Next Month": unknown
		"Next Week": unknown
		"Next Year": unknown
		"Nextcloud, Fastmail, Radicale — any CalDAV server": unknown
		"No matches": unknown
		"No release notes available": unknown
		"Notion.TokenHint": unknown
		"now current date jump": unknown
		"Occurrences": unknown
		"of event at ${time}": unknown
		"OK": unknown
		"On": unknown
		"Open in Google Maps": unknown
		"Options": unknown
		"Password": unknown
		"Previous Month": unknown
		"Previous Week": unknown
		"Previous Year": unknown
		"Primary time zone — switch to ${city} time to change the zone": unknown
		"Re-import entries": unknown
		"Refresh": unknown
		"Reload to finish updating": unknown
		"Reminder": unknown
		"Reminders": unknown
		"Remove": unknown
		"Remove reminder": unknown
		"Rename": unknown
		"Rename time zone": unknown
		"Repeat": unknown
		"Repeats": unknown
		"Repository": unknown
		"Reset to calendar color": unknown
		"Reset to default color": unknown
		"Save": unknown
		"Search entries or run a command…": unknown
		"Search or run a command (${hotkey})": unknown
		"Search or run a command…": unknown
		"select": unknown
		"Server URL": unknown
		"Set as the default for new entries": unknown
		"Show calendar": unknown
		"Showing ${city} time — switch to the primary time zone": unknown
		"Showing the primary time zone — switch to ${city} time": unknown
		"Shown above the time axis. Leave empty to use the automatic name.": unknown
		"Sign out": unknown
		"Sources": unknown
		"Start date": unknown
		"Start time": unknown
		"switch": unknown
		"switch grid": unknown
		"Switch to all-day": unknown
		"Tasks": unknown
		"the ${ordinal}": unknown
		"the ${ordinal} ${weekday}": unknown
		"The calendars of your Google account": unknown
		"The calendars of your iCloud account": unknown
		"the last ${weekday}": unknown
		"The task databases of your workspace": unknown
		"This and following entries": unknown
		"This entry": unknown
		"Time zone": unknown
		"times": unknown
		"Title": unknown
		"To Do": unknown
		"Today": unknown
		"Toggle sidebar": unknown
		"Toggle Sidebar": unknown
		"unchanged": unknown
		"Unreleased": unknown
		"Untitled": unknown
		"Update available: ${version}": unknown
		"Username": unknown
		"version build info release commit": unknown
		"View": unknown
		"View on GitHub": unknown
		"Wall clock — no time zone": unknown
		"Week": unknown
		"Week View": unknown
		"weeks": unknown
		"What's New": unknown
		"Workspace": unknown
		"Year": unknown
		"Year View": unknown
	}
}
