import '@a11d/lit-application-native'
import '@3mo/date-time'
import '@3mo/date-time-value-constructor'
// After the @3mo packages: they register their own `de` dictionary (e.g. Week→"KW"), and the dictionary
// merge lets the last writer win — so the app's own translations must be registered last to override
// library defaults. No component calls `t()` at module-eval time, so this later position is safe.
import '../infrastructure/i18n/index.js'
// Before any component: the theme setting stamps the stored theme on <html> at module scope, and the
// shell would otherwise paint the system's answer first (see app/settings.ts).
import './settings.js'
import '../design/Icon.js'
import '../design/IconButton.js'
import '../features/entries/client/TaskStatus.js'
import '../design/Tabs.js'
import '../features/recurrence/client/RepeatField.js'
import '../features/locations/client/LocationField.js'
import '../features/reminders/client/RemindersField.js'
import '../features/participants/client/ParticipantsField.js'
import '../features/relations/client/RelationsField.js'
import '../features/time/client/TimeZoneHeader.js'
import '../features/time/client/TimeZonePicker.js'
import '../features/entries/client/EntryDetailsWhen.js'
import '../features/entries/client/EntryDetailsSharing.js'
import '../design/ColorPicker.js'
import '../design/Dialog.js'
import '../features/settings/client/SettingRow.js'
import '../features/calendar/client/Days.js'
import '../features/calendar/client/Day.js'
import './Sidebar.js'
import '../features/planning/client/Unscheduled.js'
import '../features/calendar/client/PageCalendar.js'
import './Mitra.js'
import '../features/entries/client/EventDetails.js'
import '../features/entries/client/EventSegment.js'
import '../features/calendar/client/Weeks.js'
import '../features/calendar/client/Months.js'
import '../features/calendar/client/Timeline.js'
import '../design/Markdown.js'
