import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

/**
 * i18n key generation and dictionary coverage analysis.
 */

const here = path.dirname(fileURLToPath(import.meta.url))
const srcDir = path.resolve(here, '../src')
const i18nDir = path.resolve(srcDir, 'infrastructure/i18n')
const keysFile = path.join(i18nDir, 'keys.auto-generated.ts')
const dicts = ['de.json', 'fr.json', 'es.json', 'pt.json', 'it.json']

const analyzeOnly = process.argv.includes('--analyze')

const unscannable = ['index.ts', 'keys.auto-generated.ts']

function sourceFiles(dir: string): Array<string> {
	return fs.readdirSync(dir, { withFileTypes: true }).flatMap(entry => {
		const full = path.join(dir, entry.name)
		if (entry.isDirectory()) {
			return sourceFiles(full)
		}
		if (!entry.name.endsWith('.ts') || entry.name.endsWith('.test.ts')) {
			return []
		}
		return dir === i18nDir && unscannable.includes(entry.name) ? [] : [full]
	})
}

const callPattern = /\bt\(\s*(['"])((?:\\.|(?!\1)[^\\])*)\1/g

// Collect provider class descriptions which are dynamically localized via t(class.description).
const descriptionPattern = /\bstatic\s+(?:(?:readonly|override)\s+)*description\s*(?::\s*string\s*)?=\s*(['"])((?:\\.|(?!\1)[^\\])*)\1/g

function unescape(raw: string, quote: string): string {
	return raw.replace(/\\(['"\\])/g, (_, char) => char === quote || char === '\\' ? char : `\\${char}`)
}

const keys = new Set<string>()
for (const file of sourceFiles(srcDir)) {
	const source = fs.readFileSync(file, 'utf8')
	for (const [, quote, raw] of source.matchAll(callPattern)) {
		keys.add(unescape(raw, quote!))
	}
	for (const [, quote, raw] of source.matchAll(descriptionPattern)) {
		keys.add(unescape(raw, quote!))
	}
}
const sortedKeys = [...keys].sort((a, b) => a.localeCompare(b))

if (!analyzeOnly) {
	const lines = sortedKeys.map(key => `\t\t${JSON.stringify(key)}: unknown`).join('\n')
	fs.writeFileSync(keysFile, `// <auto-generated>
// ⚠️ Do not edit this file manually. Run \`npm run i18n:generate\` to regenerate it from the \`t('…')\`
// calls in the frontend. It augments @3mo/localization's \`LocalizableStringKeys\` so \`t(…)\` autocompletes
// the known keys and flags typos, while still accepting any string.
/* eslint-disable */
export {}

declare global {
\tinterface LocalizableStringKeys {
${lines}
\t}
}
`)
	console.log(`Wrote ${sortedKeys.length} keys to ${path.relative(process.cwd(), keysFile)}`)
}

// Analyze coverage against the collected keys.
let hasError = false
for (const dict of dicts) {
	const dictPath = path.join(i18nDir, dict)
	const parsed = JSON.parse(fs.readFileSync(dictPath, 'utf8')) as Record<string, unknown>
	const missing = sortedKeys.filter(key => !(key in parsed))
	const unused = Object.keys(parsed).filter(key => !keys.has(key)).sort((a, b) => a.localeCompare(b))

	if (missing.length) {
		console.log(`\n⚠ ${missing.length} key(s) in ${dict} with no translation (will fall back to English):`)
		missing.forEach(key => console.log(`  + ${JSON.stringify(key)}`))
	}
	if (unused.length) {
		console.log(`\n⚠ ${unused.length} ${dict} key(s) no longer used in the code:`)
		unused.forEach(key => console.log(`  - ${JSON.stringify(key)}`))
	}
	if (!missing.length && !unused.length) {
		console.log(`\n✓ ${dict} is in sync with the code (${sortedKeys.length} keys).`)
	}
	if (missing.length || unused.length) {
		hasError = true
	}
}

if (analyzeOnly && hasError) {
	process.exit(1)
}
