import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

/**
 * i18n tooling. Two modes:
 *
 *   node scripts/i18n.ts            — regenerate src/infrastructure/i18n/keys.auto-generated.ts from
 *                                     every `t('…')` call under src/, then print an analysis.
 *   node scripts/i18n.ts --analyze  — analysis only (no writes); exits non-zero if any key is missing a
 *                                     German translation or any de.json key is unused. Suitable for CI.
 *
 * "Keys" are the natural-English first argument of `t(…)`; English needs no dictionary (a key with no
 * entry renders as itself), so only the translation files (de.json) are checked for drift. `t()` is a
 * frontend-only global, so scanning the whole tree (rather than picking a "frontend" subtree by name)
 * costs nothing extra — a backend-only file simply never matches.
 */

const here = path.dirname(fileURLToPath(import.meta.url))
const srcDir = path.resolve(here, '../src')
const i18nDir = path.resolve(srcDir, 'infrastructure/i18n')
const keysFile = path.join(i18nDir, 'keys.auto-generated.ts')
const dicts = ['de.json', 'fr.json', 'es.json', 'pt.json', 'it.json']

const analyzeOnly = process.argv.includes('--analyze')

/** Every non-test .ts under `dir`, except the i18n folder itself. */
function sourceFiles(dir: string): Array<string> {
	return fs.readdirSync(dir, { withFileTypes: true }).flatMap(entry => {
		const full = path.join(dir, entry.name)
		if (entry.isDirectory()) {
			// The i18n folder is infra (this script's own output + dictionaries), not scannable UI — and
			// its doc comments literally contain `t('…')`, which would otherwise be collected as a key.
			return full === i18nDir ? [] : sourceFiles(full)
		}
		if (!entry.name.endsWith('.ts') || entry.name.endsWith('.test.ts')) {
			return []
		}
		return [full]
	})
}

// A `t(` call whose first argument is a string literal (single or double quoted), tolerating escapes.
// Dynamic keys (template literals, variables) can't be indexed statically and are simply not collected.
const callPattern = /\bt\(\s*(['"])((?:\\.|(?!\1)[^\\])*)\1/g

// The add dialog's integration tiles localize each provider's `description` static (declared on the
// class in src/shared) via `t(class.description)` — a dynamic key `callPattern` can't see. Collect those
// string literals directly so their translations stay tracked like any other key. Keyed on the field
// name, so only `description` counts (a brand `label` is rendered verbatim, never translated).
const descriptionPattern = /\bstatic\s+(?:(?:readonly|override)\s+)*description\s*(?::\s*string\s*)?=\s*(['"])((?:\\.|(?!\1)[^\\])*)\1/g

/** Turn a matched literal's raw body into the actual key (unescape the quote style and backslashes). */
function unescape(raw: string, quote: string): string {
	return raw.replace(/\\(['"\\])/g, (_, char) => char === quote || char === '\\' ? char : `\\${char}`)
}

const keys = new Set<string>()
for (const file of sourceFiles(srcDir)) {
	const source = fs.readFileSync(file, 'utf8')
	for (const [, quote, raw] of source.matchAll(callPattern)) {
		keys.add(unescape(raw, quote!))
	}
	// A provider's `description` static (see Integration.ts) is what the add dialog localizes via
	// `t(class.description)` — a dynamic key `callPattern` can't see, so it's collected by shape instead.
	for (const [, quote, raw] of source.matchAll(descriptionPattern)) {
		keys.add(unescape(raw, quote!))
	}
}
const sortedKeys = [...keys].sort((a, b) => a.localeCompare(b))

if (!analyzeOnly) {
	// Each key becomes a `LocalizableStringKeys` member so `t(…)` autocompletes and flags typos.
	const lines = sortedKeys.map(key => `\t\t${JSON.stringify(key)}: unknown`).join('\n')
	fs.writeFileSync(keysFile, `// <auto-generated>
// ⚠️ Do not edit this file manually. Run \`npm run i18n:generate\` to regenerate it from the \`t('…')\`
// calls in the frontend. It augments @3mo/localization's \`LocalizableStringKeys\` so \`t(…)\` autocompletes
// the known keys and flags typos, while still accepting any string.
/* eslint-disable */
export {}

declare global {
\tinterface LocalizableStringKeys {
${lines}
\t}
}
`)
	console.log(`Wrote ${sortedKeys.length} keys to ${path.relative(process.cwd(), keysFile)}`)
}

// Analyze coverage against the collected keys.
let hasError = false
for (const dict of dicts) {
	const dictPath = path.join(i18nDir, dict)
	const parsed = JSON.parse(fs.readFileSync(dictPath, 'utf8')) as Record<string, unknown>
	const missing = sortedKeys.filter(key => !(key in parsed))
	const unused = Object.keys(parsed).filter(key => !keys.has(key)).sort((a, b) => a.localeCompare(b))

	if (missing.length) {
		console.log(`\n⚠ ${missing.length} key(s) in ${dict} with no translation (will fall back to English):`)
		missing.forEach(key => console.log(`  + ${JSON.stringify(key)}`))
	}
	if (unused.length) {
		console.log(`\n⚠ ${unused.length} ${dict} key(s) no longer used in the code:`)
		unused.forEach(key => console.log(`  - ${JSON.stringify(key)}`))
	}
	if (!missing.length && !unused.length) {
		console.log(`\n✓ ${dict} is in sync with the code (${sortedKeys.length} keys).`)
	}
	if (missing.length || unused.length) {
		hasError = true
	}
}

if (analyzeOnly && hasError) {
	process.exit(1)
}
