// <auto-generated>
// ⚠️ Do not edit this file manually. Run `npm run i18n:generate` to regenerate it from the `t('…')`
// calls in the frontend. It augments @3mo/localization's `LocalizableStringKeys` so `t(…)` autocompletes
// the known keys and flags typos, while still accepting any string.
/* eslint-disable */
export {}

declare global {
	interface LocalizableStringKeys {
		"\"${heading}\" could not be added: ${message}": unknown
		"\"${heading}\" could not be copied: ${message}": unknown
		"\"${heading}\" is closed, but ${count:pluralityNumber} of its subtasks are still open.": unknown
		"${count:number} min": unknown
		"${count:number} more": unknown
		"${count:pluralityNumber} are marked as free": unknown
		"${count:pluralityNumber} are now in both calendars": unknown
		"${count:pluralityNumber} arrive with everything they carry": unknown
		"${count:pluralityNumber} become ${type}": unknown
		"${count:pluralityNumber} belong to a series with edited occurrences": unknown
		"${count:pluralityNumber} carry a progress percentage": unknown
		"${count:pluralityNumber} carry a visibility": unknown
		"${count:pluralityNumber} copies could not be taken back and are now in both calendars.": unknown
		"${count:pluralityNumber} days": unknown
		"${count:pluralityNumber} entries": unknown
		"${count:pluralityNumber} entries added to ${name}": unknown
		"${count:pluralityNumber} entries arrive, the flattened series included": unknown
		"${count:pluralityNumber} entries copied to ${name}": unknown
		"${count:pluralityNumber} entries moved to ${name}": unknown
		"${count:pluralityNumber} have participants": unknown
		"${count:pluralityNumber} hours": unknown
		"${count:pluralityNumber} landed anyway and could not be taken back. Delete them in ${name} by hand.": unknown
		"${count:pluralityNumber} lose their cancelled status": unknown
		"${count:pluralityNumber} lose their description": unknown
		"${count:pluralityNumber} lose their location": unknown
		"${count:pluralityNumber} lose their reminders": unknown
		"${count:pluralityNumber} lose their time zone": unknown
		"${count:pluralityNumber} of ${total:number} entries are added": unknown
		"${count:pluralityNumber} of ${total:number} entries are copied": unknown
		"${count:pluralityNumber} of ${total:number} entries move": unknown
		"${count:pluralityNumber} participants": unknown
		"${count:pluralityNumber} repeat": unknown
		"${count:pluralityNumber} repeating entries: every occurrence goes too.": unknown
		"${count:pluralityNumber} selected": unknown
		"${count:pluralityNumber} stayed in ${name}": unknown
		"${count:pluralityNumber} stop being all-day": unknown
		"${count:pluralityNumber} weeks": unknown
		"${count:pluralityNumber} were left out": unknown
		"${done} of ${total:pluralityNumber} checklist items done": unknown
		"${done} of ${total:pluralityNumber} steps done": unknown
		"${done} of ${total:pluralityNumber} subtasks done": unknown
		"${n:number}nd": unknown
		"${n:number}rd": unknown
		"${n:number}st": unknown
		"${n:number}th": unknown
		"${names} and ${count:pluralityNumber} more": unknown
		"${percent} complete": unknown
		"${reason}, kept here": unknown
		"${reason}, left out": unknown
		"${rule} until ${date}": unknown
		"${rule}, ${count:pluralityNumber} times": unknown
		"${span} before": unknown
		"${status}. Click to toggle, Alt-click for options": unknown
		"About": unknown
		"About.Keywords": unknown
		"Account": unknown
		"Account options": unknown
		"Add ${count:pluralityNumber} entries": unknown
		"Add ${name} to a calendar": unknown
		"Add integration": unknown
		"Add Integration": unknown
		"Add participant": unknown
		"Add participants": unknown
		"Add relationship": unknown
		"Add reminder": unknown
		"Add Task": unknown
		"Add time zone": unknown
		"Add to ${name}": unknown
		"Add your first integration": unknown
		"Added to ${name}": unknown
		"Adding ${count:pluralityNumber} entries…": unknown
		"AddIntegration.Keywords": unknown
		"Administration": unknown
		"After": unknown
		"All day": unknown
		"All entries": unknown
		"All entries in this calendar will be deleted too. This can't be undone.": unknown
		"All subtasks done": unknown
		"Allow": unknown
		"Allowed": unknown
		"Alt+click to show only this one": unknown
		"Alt+click to show the previously visible ones": unknown
		"Amount": unknown
		"Any CalDAV server, like Nextcloud, Fastmail or Radicale": unknown
		"Any calendar link (webcal:// or .ics)": unknown
		"App-Specific Password": unknown
		"Apple Calendar": unknown
		"Apple ID": unknown
		"Apply to subtasks too?": unknown
		"Ask everyone to attend": unknown
		"Ask this participant to attend": unknown
		"At start": unknown
		"At start of event": unknown
		"Atlassian Account": unknown
		"Atlassian Account E-mail": unknown
		"Atlassian API Token": unknown
		"Back": unknown
		"before": unknown
		"before at ${time}": unknown
		"Blocked": unknown
		"Blocked by": unknown
		"Blocks": unknown
		"Busy": unknown
		"CalDAV": unknown
		"CalDAV, Google, Apple or Notion, synced in both directions. Or start fresh with calendars stored in Mitra itself.": unknown
		"Calendar": unknown
		"Calendar name": unknown
		"Calendar options": unknown
		"Calendar Subscription": unknown
		"Calendar URL": unknown
		"Calendars": unknown
		"Calendars stored in Mitra itself, no account needed": unknown
		"Cancelled": unknown
		"Change ${name}…": unknown
		"Checking what the calendar can take…": unknown
		"Checking what would be copied…": unknown
		"Checking what would move…": unknown
		"Choose a date": unknown
		"Choose a task status": unknown
		"Choose a time": unknown
		"Choose the calendar the entries of this file are added to. The ones it cannot take are left out. The file itself stays untouched.": unknown
		"Choose your sources": unknown
		"Clear custom progress": unknown
		"Clear filter": unknown
		"Clear selection": unknown
		"click": unknown
		"close": unknown
		"Close": unknown
		"Close out the subtasks that are still open": unknown
		"Color": unknown
		"Columns": unknown
		"Commands": unknown
		"Commit": unknown
		"Confidential": unknown
		"Connect": unknown
		"Connect an account": unknown
		"Connecting…": unknown
		"Connector lines in the month view": unknown
		"Connector lines in the timeline": unknown
		"Connector lines in the week view": unknown
		"ConnectorLines.Keywords": unknown
		"Continue with Google": unknown
		"Copied to ${name}": unknown
		"Copy": unknown
		"Copy ${count:pluralityNumber} entries": unknown
		"Copy entries from ${name}…": unknown
		"Copy entries to another calendar": unknown
		"Copy entries to…": unknown
		"Copy every entry into another calendar": unknown
		"Copy instead": unknown
		"Copy participants' emails": unknown
		"Copy to ${name}": unknown
		"Copy Version": unknown
		"Copying ${count:pluralityNumber} entries…": unknown
		"CopyVersion.Keywords": unknown
		"Could not load your devices.": unknown
		"Create": unknown
		"Create and move entries right on the grid. Every change syncs back to its source.": unknown
		"Create Entry": unknown
		"CreateEntry.Keywords": unknown
		"Ctrl": unknown
		"Custom range": unknown
		"Custom…": unknown
		"Dark": unknown
		"Date": unknown
		"days": unknown
		"Default Calendar": unknown
		"Default Duration": unknown
		"Default for new entries, as the first one shown": unknown
		"Default for new entries. Click to unset": unknown
		"Default Reminder": unknown
		"Default View": unknown
		"Default visibility": unknown
		"DefaultDurationSetting.Keywords": unknown
		"DefaultReminderSetting.Keywords": unknown
		"DefaultSourceSetting.Keywords": unknown
		"DefaultViewSetting.Keywords": unknown
		"Del": unknown
		"Delete": unknown
		"Delete \"${name}\"?": unknown
		"Delete ${count:pluralityNumber} entries?": unknown
		"Delete calendar": unknown
		"Delete entry": unknown
		"Delete just this entry of a series": unknown
		"Delete repeating entry": unknown
		"Delete subtasks too?": unknown
		"Delete the open entry": unknown
		"Delete this calendar and every entry in it": unknown
		"Demo": unknown
		"Demo.Hint": unknown
		"Description": unknown
		"Devices": unknown
		"Does not repeat": unknown
		"Doing": unknown
		"Done": unknown
		"Done and cancelled tasks leave the calendar. Search still finds them, and they still count towards progress.": unknown
		"Double-click to rename": unknown
		"Draft": unknown
		"drag": unknown
		"Drag onto another entry to make it wait for this one": unknown
		"Duplicate": unknown
		"Duplicate an entry": unknown
		"Duration": unknown
		"Edit": unknown
		"Edit entry": unknown
		"Edit integration": unknown
		"Edit repeating entry": unknown
		"Email participants": unknown
		"End date": unknown
		"End time": unknown
		"Ends": unknown
		"Entries": unknown
		"Event": unknown
		"Events": unknown
		"Every": unknown
		"Every ${count:pluralityNumber} days": unknown
		"Every ${count:pluralityNumber} months": unknown
		"Every ${count:pluralityNumber} weeks": unknown
		"Every ${count:pluralityNumber} years": unknown
		"Every entry in ${name} is copied. The ones the chosen calendar cannot take are left out. ${name} itself is read-only and stays exactly as it is.": unknown
		"Every entry in ${name} moves. The ones the chosen calendar cannot take stay here.": unknown
		"Every entry is still in ${name}. Nothing was deleted.": unknown
		"Every subtask of \"${heading}\" is done, which completes ${count:pluralityNumber} more tasks above it. Mark them all as done?": unknown
		"Every subtask of \"${heading}\" is done. Mark it as done too?": unknown
		"Every weekday": unknown
		"Everything travels intact": unknown
		"Flatten into single entries": unknown
		"Flattening writes out a year of occurrences as separate entries. They stop repeating, and links pointing at the series are left behind.": unknown
		"Forward": unknown
		"Free": unknown
		"Frequency": unknown
		"From": unknown
		"From ${date}": unknown
		"General": unknown
		"Go to Date…": unknown
		"Go to entry": unknown
		"Go to Today": unknown
		"Google account": unknown
		"Google Calendar": unknown
		"Google.ConfigurationHint": unknown
		"Google.ConsentHint": unknown
		"Google.SharedCalendarsHint": unknown
		"GoToDate.Keywords": unknown
		"GoToToday.Keywords": unknown
		"Hide calendar": unknown
		"Hide column": unknown
		"Hide done tasks": unknown
		"Hide the other time zones": unknown
		"HideDoneTasksSetting.Keywords": unknown
		"hours": unknown
		"Ics.UrlHint": unknown
		"Importing entries…": unknown
		"Include time": unknown
		"Install as an App": unknown
		"Install mitra as an app. It gets its own window, and notifications appear under its own name and icon": unknown
		"Integration options": unknown
		"Integration Token": unknown
		"Interval": unknown
		"Keep": unknown
		"Keep the calendar": unknown
		"Keep the chain intact": unknown
		"Keyboard Shortcuts": unknown
		"KeyboardShortcuts.Keywords": unknown
		"Language": unknown
		"LanguageSetting.Keywords": unknown
		"last seen ${when}": unknown
		"Leave the originals here and add a copy over there": unknown
		"Leave them here": unknown
		"Light": unknown
		"Location": unknown
		"Make attendance optional": unknown
		"Make attendance optional for everyone": unknown
		"Mark all as done": unknown
		"Mark all optional": unknown
		"Mark all required": unknown
		"Mark as cancelled": unknown
		"Mark as done": unknown
		"Match the system": unknown
		"minutes": unknown
		"Mitra": unknown
		"Mitra.Hint": unknown
		"modified": unknown
		"Month": unknown
		"Month View": unknown
		"MonthView.Keywords": unknown
		"Move ${count:pluralityNumber} entries": unknown
		"Move dependent entries too?": unknown
		"Move down": unknown
		"Move entries first…": unknown
		"Move entries from ${name}…": unknown
		"Move entries to another calendar": unknown
		"Move entries to…": unknown
		"Move entry": unknown
		"Move or copy every entry into another calendar": unknown
		"Move or resize just this entry of a series": unknown
		"Move repeating entry": unknown
		"Move subtasks too?": unknown
		"Move them all by the same amount": unknown
		"Move to ${name}": unknown
		"Move to…": unknown
		"Move up": unknown
		"Moved to ${name}": unknown
		"MoveSourceEntries.Keywords": unknown
		"Moving ${count:pluralityNumber} entries…": unknown
		"Name": unknown
		"navigate": unknown
		"Navigation": unknown
		"never": unknown
		"Never": unknown
		"New calendar": unknown
		"New dev build: ${count:pluralityNumber} commits ahead": unknown
		"New task": unknown
		"Next 12 months": unknown
		"Next 30 days": unknown
		"Next 7 days": unknown
		"Next month": unknown
		"Next Month": unknown
		"Next Week": unknown
		"Next Year": unknown
		"NextPeriod.Keywords": unknown
		"No date": unknown
		"No device is registered for reminders yet.": unknown
		"No entries in this period": unknown
		"No entries match the filters": unknown
		"No matches": unknown
		"No matching entries": unknown
		"No release notes available": unknown
		"No status": unknown
		"None": unknown
		"Nothing from the file was added.": unknown
		"Nothing is deleted here until its copy has landed": unknown
		"Nothing planned yet. Draw a task on the row below": unknown
		"Nothing was added": unknown
		"Nothing was copied": unknown
		"Nothing was moved": unknown
		"Notifications": unknown
		"NotificationsSetting.Keywords": unknown
		"Notion": unknown
		"Notion.TokenHint": unknown
		"Occurrences": unknown
		"of event at ${time}": unknown
		"On": unknown
		"on ${date}": unknown
		"on ${weekday}": unknown
		"on the ${ordinal}": unknown
		"on the ${ordinal} ${weekday}": unknown
		"on the last ${weekday}": unknown
		"One calendar to plan your events and tasks": unknown
		"Only Show ${name}": unknown
		"Only show this calendar": unknown
		"Only the organizer can change participants": unknown
		"Only this entry": unknown
		"Open in ${provider}": unknown
		"Open in Google Maps": unknown
		"Open link": unknown
		"OpenSettings.Keywords": unknown
		"Optional": unknown
		"Options": unknown
		"or": unknown
		"Organizer": unknown
		"Overdue": unknown
		"Participant options": unknown
		"Participants": unknown
		"Password": unknown
		"Password (optional)": unknown
		"Past 30 days": unknown
		"Pick the calendars and task lists to show. Recolor, rename or hide them in the sidebar anytime.": unknown
		"Plan your days": unknown
		"Planning": unknown
		"Previous month": unknown
		"Previous Month": unknown
		"Previous Week": unknown
		"Previous Year": unknown
		"PreviousPeriod.Keywords": unknown
		"Primary": unknown
		"Primary time zone. Switch to ${city} time to change the zone": unknown
		"Private": unknown
		"Progress": unknown
		"Public": unknown
		"Re-import entries": unknown
		"Read every enabled calendar of this account again from the start": unknown
		"Read this calendar again from the start": unknown
		"read-only": unknown
		"Refresh": unknown
		"Related to": unknown
		"Reload to finish updating": unknown
		"Reminder": unknown
		"Reminder notifications": unknown
		"Reminders": unknown
		"Reminders you add are always saved; this decides whether this browser may also alert you.": unknown
		"Remove": unknown
		"Remove all": unknown
		"Remove every participant": unknown
		"Remove participant": unknown
		"Remove relationship": unknown
		"Remove reminder": unknown
		"Remove the date": unknown
		"Remove the date. The task moves to Unscheduled": unknown
		"Remove the end date": unknown
		"Rename": unknown
		"Rename time zone": unknown
		"Repeat": unknown
		"Repeating": unknown
		"Repeating entries cannot repeat in ${name}": unknown
		"Repeats": unknown
		"Repository": unknown
		"Reset columns": unknown
		"Reset to calendar color": unknown
		"Reset to default color": unknown
		"Sample calendars filled with generated data, rebuilt daily": unknown
		"Save": unknown
		"scroll": unknown
		"Search entries or run a command…": unknown
		"Search entries…": unknown
		"Search for an event or task to link": unknown
		"Search or run a command (${hotkey})": unknown
		"Search or run a command…": unknown
		"Search settings…": unknown
		"select": unknown
		"Select": unknown
		"Select all": unknown
		"Send test": unknown
		"Server URL": unknown
		"Set as the default for new entries": unknown
		"Settings": unknown
		"Show as busy or free": unknown
		"Show calendar": unknown
		"Show fewer participants": unknown
		"Show only one calendar, or bring the rest back": unknown
		"Show previously visible calendars": unknown
		"Show Previously Visible Calendars": unknown
		"Show the other time zones": unknown
		"Showing ${city} time. Switch to the primary time zone": unknown
		"Showing the primary time zone. Switch to ${city} time": unknown
		"Shown above the time axis. Leave empty to use the automatic name.": unknown
		"ShowOnlySource.Keywords": unknown
		"ShowPreviouslyVisibleSources.Keywords": unknown
		"Sign out": unknown
		"Site URL": unknown
		"Snap to": unknown
		"SnapSetting.Keywords": unknown
		"Sort ascending": unknown
		"Sort descending": unknown
		"Sources": unknown
		"Start date": unknown
		"Start time": unknown
		"Status": unknown
		"Stop notifying this device": unknown
		"Subtask of": unknown
		"Subtasks": unknown
		"Subtasks still open": unknown
		"Switch to all-day": unknown
		"Table": unknown
		"Table View": unknown
		"TableView.Keywords": unknown
		"Task": unknown
		"Tasks": unknown
		"Tasks without a date land here. Drag one onto the calendar to schedule it": unknown
		"Tempo": unknown
		"Tempo API Token": unknown
		"Tempo.TokenHint": unknown
		"Test notification sent.": unknown
		"the ${ordinal}": unknown
		"the ${ordinal} ${weekday}": unknown
		"The calendars of your Google account": unknown
		"The calendars of your iCloud account": unknown
		"The file stays exactly as it is": unknown
		"The hours you book on Jira issues": unknown
		"the last ${weekday}": unknown
		"The originals stay exactly where they are": unknown
		"The step dragging and resizing land on": unknown
		"The task databases of your workspace": unknown
		"Their copies landed but the originals could not be deleted. Delete them here by hand.": unknown
		"Theme": unknown
		"ThemeSetting.Keywords": unknown
		"There is no calendar the file could be added to.": unknown
		"There is no other calendar these entries could move to.": unknown
		"This and following entries": unknown
		"This and its ${count:pluralityNumber} subtasks": unknown
		"This browser is blocking notifications. Allow them in its site settings to get reminders here.": unknown
		"This browser will show your reminders.": unknown
		"this device": unknown
		"This entry": unknown
		"This relationship could not be saved": unknown
		"This relationship is not possible": unknown
		"Time zone": unknown
		"Timed entries only": unknown
		"Timeline": unknown
		"Timeline View": unknown
		"TimelineView.Keywords": unknown
		"times": unknown
		"Tip: hold ${modifier} to skip this dialog and apply to this entry only": unknown
		"Title": unknown
		"To Do": unknown
		"Today": unknown
		"Toggle sidebar": unknown
		"Toggle Sidebar": unknown
		"Toggle.Off": unknown
		"Toggle.On": unknown
		"ToggleSidebar.Keywords": unknown
		"Type": unknown
		"unchanged": unknown
		"Unit": unknown
		"Unknown device": unknown
		"Unknown entry": unknown
		"Unreleased": unknown
		"Unscheduled": unknown
		"Until": unknown
		"Untitled": unknown
		"Update available: ${version}": unknown
		"Username": unknown
		"Username (optional)": unknown
		"View": unknown
		"View on GitHub": unknown
		"Views": unknown
		"Visibility": unknown
		"Wall clock (no time zone)": unknown
		"Week": unknown
		"Week ${week:number}": unknown
		"Week View": unknown
		"Weekdays": unknown
		"weeks": unknown
		"WeekView.Keywords": unknown
		"Welcome to ${name}": unknown
		"What's New": unknown
		"WhatsNew.Keywords": unknown
		"When": unknown
		"Where new events and tasks are created": unknown
		"Workspace": unknown
		"Year": unknown
		"Year View": unknown
		"YearView.Keywords": unknown
		"Zoom the view": unknown
	}
}
