// <auto-generated>
// ⚠️ Do not edit this file manually. Run `npm run i18n:generate` to regenerate it from the `t('…')`
// calls in the frontend. It augments @3mo/localization's `LocalizableStringKeys` so `t(…)` autocompletes
// the known keys and flags typos, while still accepting any string.
/* eslint-disable */
export {}

declare global {
	interface LocalizableStringKeys {
		"\"${heading}\" is closed, but ${count:pluralityNumber} of its subtasks are still open.": unknown
		"+${count:number} more": unknown
		"${count:number} min": unknown
		"${count:number} more": unknown
		"${count:pluralityNumber} days": unknown
		"${count:pluralityNumber} entries": unknown
		"${count:pluralityNumber} hours": unknown
		"${count:pluralityNumber} months": unknown
		"${count:pluralityNumber} participants": unknown
		"${count:pluralityNumber} weeks": unknown
		"${count:pluralityNumber} years": unknown
		"${done} of ${total:pluralityNumber} subtasks done": unknown
		"${percent}% complete": unknown
		"${span} before": unknown
		"${status} — click to toggle, Alt-click for options": unknown
		"About": unknown
		"About.Keywords": unknown
		"Account": unknown
		"Add integration": unknown
		"Add Integration": unknown
		"Add participant": unknown
		"Add participants": unknown
		"Add relationship": unknown
		"Add reminder": unknown
		"Add Task": unknown
		"Add time zone": unknown
		"Add your first integration": unknown
		"AddIntegration.Keywords": unknown
		"After": unknown
		"All day": unknown
		"All entries": unknown
		"All subtasks done": unknown
		"Alt+click to show only this one": unknown
		"Alt+click to show the previously visible ones": unknown
		"Amount": unknown
		"Any calendar link — webcal:// or .ics": unknown
		"App-Specific Password": unknown
		"Apple ID": unknown
		"Apply to subtasks too?": unknown
		"Ask everyone to attend": unknown
		"Ask this participant to attend": unknown
		"At start": unknown
		"At start of event": unknown
		"Atlassian Account": unknown
		"Atlassian Account E-mail": unknown
		"Atlassian API Token": unknown
		"Back": unknown
		"before": unknown
		"before at ${time}": unknown
		"Blocked by": unknown
		"Blocks": unknown
		"Busy": unknown
		"CalDAV, Google, Apple or Notion — Mitra syncs in both directions.": unknown
		"Calendar": unknown
		"Calendar options": unknown
		"Calendar URL": unknown
		"Calendars": unknown
		"Cancelled": unknown
		"Choose a task status": unknown
		"Choose your sources": unknown
		"Clear custom progress": unknown
		"click": unknown
		"close": unknown
		"Close": unknown
		"Close out the subtasks that are still open": unknown
		"Color": unknown
		"Commands": unknown
		"Commit": unknown
		"Confidential": unknown
		"Connect": unknown
		"Connect an account": unknown
		"Connecting…": unknown
		"Continue with Google": unknown
		"Copy": unknown
		"Copy participants' emails": unknown
		"Copy Version": unknown
		"CopyVersion.Keywords": unknown
		"Create and move entries right on the grid — every change syncs back to its source.": unknown
		"Create Entry": unknown
		"CreateEntry.Keywords": unknown
		"Ctrl": unknown
		"Custom…": unknown
		"Date": unknown
		"days": unknown
		"Default for new entries — click to unset": unknown
		"Default for new entries, as the first one shown": unknown
		"Default visibility": unknown
		"Del": unknown
		"Delete": unknown
		"Delete entry": unknown
		"Delete just this entry of a series": unknown
		"Delete repeating entry": unknown
		"Delete subtasks too?": unknown
		"Delete the locally cached entries and import everything from the source again": unknown
		"Delete the locally cached entries of every enabled source and import everything again": unknown
		"Delete the open entry": unknown
		"Description": unknown
		"Does not repeat": unknown
		"Doing": unknown
		"Done": unknown
		"Double-click to rename": unknown
		"Draft": unknown
		"drag": unknown
		"Drag onto another entry to make it wait for this one": unknown
		"Duplicate": unknown
		"Duplicate an entry": unknown
		"Edit": unknown
		"Edit entry": unknown
		"Edit integration": unknown
		"Edit repeating entry": unknown
		"Email participants": unknown
		"End date": unknown
		"End time": unknown
		"Ends": unknown
		"Entries": unknown
		"Event": unknown
		"Events": unknown
		"Every": unknown
		"Every subtask of \"${heading}\" is done, which completes ${count:pluralityNumber} more tasks above it. Mark them all as done?": unknown
		"Every subtask of \"${heading}\" is done. Mark it as done too?": unknown
		"Forward": unknown
		"Free": unknown
		"General": unknown
		"Go to Date…": unknown
		"Go to entry": unknown
		"Go to Today": unknown
		"Google account": unknown
		"Google.ConfigurationHint": unknown
		"Google.ConsentHint": unknown
		"Google.SharedCalendarsHint": unknown
		"GoToDate.Keywords": unknown
		"GoToToday.Keywords": unknown
		"Hide calendar": unknown
		"Hide the other time zones": unknown
		"hours": unknown
		"Ics.UrlHint": unknown
		"Include time": unknown
		"Install as an App": unknown
		"Install mitra as an app — it gets its own window, and notifications appear under its own name and icon": unknown
		"Integration options": unknown
		"Integration Token": unknown
		"Interval": unknown
		"Keep the chain intact": unknown
		"Keyboard Shortcuts": unknown
		"KeyboardShortcuts.Keywords": unknown
		"Location": unknown
		"Make attendance optional": unknown
		"Make attendance optional for everyone": unknown
		"Mark all as done": unknown
		"Mark all optional": unknown
		"Mark all required": unknown
		"Mark as cancelled": unknown
		"Mark as done": unknown
		"minutes": unknown
		"modified": unknown
		"Month": unknown
		"Month View": unknown
		"MonthView.Keywords": unknown
		"Move dependent entries too?": unknown
		"Move down": unknown
		"Move entry": unknown
		"Move or resize just this entry of a series": unknown
		"Move repeating entry": unknown
		"Move subtasks too?": unknown
		"Move them all by the same amount": unknown
		"Move up": unknown
		"navigate": unknown
		"Navigation": unknown
		"Never": unknown
		"New dev build — ${count:pluralityNumber} commits ahead": unknown
		"New task": unknown
		"Next Month": unknown
		"Next Week": unknown
		"Next Year": unknown
		"Nextcloud, Fastmail, Radicale — any CalDAV server": unknown
		"NextPeriod.Keywords": unknown
		"No date": unknown
		"No matches": unknown
		"No matching entries": unknown
		"No release notes available": unknown
		"None": unknown
		"Nothing planned yet — draw a task on the row below": unknown
		"Notion.TokenHint": unknown
		"Occurrences": unknown
		"of event at ${time}": unknown
		"On": unknown
		"One calendar to plan your events and tasks": unknown
		"Only Show ${name}": unknown
		"Only show this calendar": unknown
		"Only the organizer can change participants": unknown
		"Only this entry": unknown
		"Open in ${provider}": unknown
		"Open in Google Maps": unknown
		"Open link": unknown
		"Optional": unknown
		"Options": unknown
		"or": unknown
		"Organizer": unknown
		"Participant options": unknown
		"Password": unknown
		"Password (optional)": unknown
		"Pick the calendars and task lists to show — recolor, rename or hide them in the sidebar anytime.": unknown
		"Plan your days": unknown
		"Planning": unknown
		"Previous Month": unknown
		"Previous Week": unknown
		"Previous Year": unknown
		"PreviousPeriod.Keywords": unknown
		"Primary time zone — switch to ${city} time to change the zone": unknown
		"Private": unknown
		"Progress": unknown
		"Public": unknown
		"Re-import entries": unknown
		"read-only": unknown
		"Refresh": unknown
		"Related to": unknown
		"Reload to finish updating": unknown
		"Reminder": unknown
		"Reminders": unknown
		"Remove": unknown
		"Remove all": unknown
		"Remove every participant": unknown
		"Remove participant": unknown
		"Remove relationship": unknown
		"Remove reminder": unknown
		"Remove the date": unknown
		"Remove the date — the task moves to Unscheduled": unknown
		"Remove the end date": unknown
		"Rename": unknown
		"Rename time zone": unknown
		"Repeat": unknown
		"Repeats": unknown
		"Repository": unknown
		"Reset to calendar color": unknown
		"Reset to default color": unknown
		"Save": unknown
		"scroll": unknown
		"Search entries or run a command…": unknown
		"Search entries…": unknown
		"Search for an event or task to link": unknown
		"Search or run a command (${hotkey})": unknown
		"Search or run a command…": unknown
		"select": unknown
		"Server URL": unknown
		"Set as the default for new entries": unknown
		"Show as busy or free": unknown
		"Show calendar": unknown
		"Show fewer participants": unknown
		"Show only one calendar, or bring the rest back": unknown
		"Show previously visible calendars": unknown
		"Show Previously Visible Calendars": unknown
		"Show the other time zones": unknown
		"Showing ${city} time — switch to the primary time zone": unknown
		"Showing the primary time zone — switch to ${city} time": unknown
		"Shown above the time axis. Leave empty to use the automatic name.": unknown
		"ShowOnlySource.Keywords": unknown
		"ShowPreviouslyVisibleSources.Keywords": unknown
		"Sign out": unknown
		"Site URL": unknown
		"Sources": unknown
		"Start date": unknown
		"Start time": unknown
		"Subtask of": unknown
		"Subtasks": unknown
		"Subtasks still open": unknown
		"Switch to all-day": unknown
		"Task": unknown
		"Tasks": unknown
		"Tasks without a date land here — drag one onto the calendar to schedule it": unknown
		"Tempo API Token": unknown
		"Tempo.TokenHint": unknown
		"the ${ordinal}": unknown
		"the ${ordinal} ${weekday}": unknown
		"The calendars of your Google account": unknown
		"The calendars of your iCloud account": unknown
		"The hours you book on Jira issues": unknown
		"the last ${weekday}": unknown
		"The task databases of your workspace": unknown
		"This and following entries": unknown
		"This and its ${count:pluralityNumber} subtasks": unknown
		"This entry": unknown
		"This relationship could not be saved": unknown
		"This relationship is not possible": unknown
		"Time zone": unknown
		"Timeline": unknown
		"Timeline View": unknown
		"TimelineView.Keywords": unknown
		"times": unknown
		"Tip: hold ${modifier} to skip this dialog and apply to this entry only": unknown
		"Title": unknown
		"To Do": unknown
		"Today": unknown
		"Toggle sidebar": unknown
		"Toggle Sidebar": unknown
		"ToggleSidebar.Keywords": unknown
		"unchanged": unknown
		"Unknown entry": unknown
		"Unreleased": unknown
		"Unscheduled": unknown
		"Untitled": unknown
		"Update available: ${version}": unknown
		"Username": unknown
		"Username (optional)": unknown
		"View": unknown
		"View on GitHub": unknown
		"Views": unknown
		"Visibility": unknown
		"Wall clock — no time zone": unknown
		"Week": unknown
		"Week View": unknown
		"weeks": unknown
		"WeekView.Keywords": unknown
		"Welcome to ${name}": unknown
		"What's New": unknown
		"WhatsNew.Keywords": unknown
		"Workspace": unknown
		"Year": unknown
		"Year View": unknown
		"YearView.Keywords": unknown
		"Zoom the view": unknown
	}
}
